name: 'Setup ecm-distro-tools'
description: 'Installs ecm-distro-tools scripts to the PATH.'
inputs:
  version:
    description: 'The tag of the ecm-distro-tools release to install.'
    required: true
runs:
  using: 'composite'
  steps:
  - shell: bash
    run: |
      TAG="${{ inputs.version }}"
      REPO="rancher/ecm-distro-tools"
      DOWNLOAD_DIR="$RUNNER_TEMP/ecm-distro-tools"
      BIN_DIR="${{ github.action_path }}/bin"
      mkdir -p "$DOWNLOAD_DIR"
      cp -r "$BIN_DIR/*" "$DOWNLOAD_DIR/"
      gh release download "$TAG" --repo "$REPO" --dir "$DOWNLOAD_DIR"
      echo "$DOWNLOAD_DIR" >> "$GITHUB_PATH"
      chmod +x "$DOWNLOAD_DIR/*"
      ls -al "$DOWNLOAD_DIR"
branding:
  icon: terminal
  color: green
